name: build-and-test
on:
  push: 
    branches:
      - feature/*
      
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup dependencies
        run: sudo apt update && sudo apt install -y swig

      - name: autogen
        working-directory: cola
        run: ./autogen.sh

      - name: make dotnet
        working-directory: cola
        run: make -f Makefile-swig-csharp
      
      

